export const UPDATE_DASH = 'UPDATE_DASH';
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES';
export const UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS';
export const UPDATE_TRANSACTIONS = 'UPDATE_TRANSACTIONS';
export const UPDATE_SETTINGS_INFO = 'UPDATE_SETTINGS_INFO';
